'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Provider, useDispatch } from "react-redux";
import store, { login } from "./store";
import { useEffect } from "react";
import { loadUserFromLocalStorage } from "./utils/auth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <AppInitializer>
            <Header />
            {children}
            <Footer />
          </AppInitializer>
        </Provider>

      </body>
    </html>
  );
}

function AppInitializer({ children }) {
  const dispatch = useDispatch();

  useEffect(() => {
    loadUserFromLocalStorage(dispatch, login);
  }, [dispatch]);

  return children;
}