# Generated by Django 4.2.13 on 2024-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
