# Generated by Django 4.2.13 on 2024-06-15 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_event_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='invited_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
